### ISSUE TITLE
Backpacks make items dissapear

### ISSUE THREAD

**Issue by catronomix** [Just1Developer/MC_Backpacks#1]
A severe issue: items are not stored in the backpack after closing it and instead just dissappear!
This makes the plugin unusable :/ No errors in console.

Running purpur 1.20.1

list of plugins:
AdvancedBan, Backpacks, CoreProtect, DiscordSRV, Essentials, EssentialsChat, EssentialsSpawn, GriefDefender, GSit, HeadsPlus, LevelledMobs, LuckPerms, mcMMO, OpenAudioMc, PotionStacker, ProtocolLib, spark, TreysDoubleJump, Vault, ViaBackwards, ViaVersion, ViewDistanceTweaks, WaystonesPlus, WorldBorder, WorldEdit, XPBoost

**Comment by catronomix** [comment]
additional info: disabling backpacks-inside-backpacks makes items saved inside the backpack, setting it to enabled makes items dissappear. Also the backpack size is ignored, I set it to 18 but still get 4 rows

**Comment by Just1Developer** [comment]
Hey, sorry this flew right past me. Very confusing issue you got there, thank you for providing a list of all the plugins.

I'm looking into the code right now and am attempting to find the bug, but I can't test anything until I get home Friday evening / Saturday (I don't have minecraft or a server here). If I think I have a solution I'm happy to provide it to you earlier, but I can't guarantee that it will work.

**Comment by Just1Developer** [comment]
The size should be fixed now, though it will only apply to new backpacks, not existing ones.
Please try it out on your server.
I went through the code and found no issues that could be causing the issue with the item saving. If the issue persists, I'd like to work with you to resolve that. Feel free to add me on discord for quicker communication: justonedeveloper

Link to the dev build: https://github.com/Just1Developer/MC_Backpacks/releases/tag/v1.5_spigot_1.20

**Comment by Just1Developer** [comment]
Hey, I'm going to close this now due to inactivity. If the issue persists, feel free to reopen this ticket, open up another one, leave a message in the discussion tab on Spigot or DM me on Discord
